name: Admin Panel Task — User, Catalog, Terminal Management
description: Complete Admin interfaces and production configuration for lab rollout
title: "[Admin]: Build UI for user, test catalog, and terminal management"
labels: ["feature", "admin", "frontend", "backend", "high priority"]
assignees:
  - your-username

body:
  - type: markdown
    attributes:
      value: |
        ## 🧱 Overview

        You are completing the Admin functionality for the LIMS system. This includes full UI support for user management, test catalog management, and terminal setup for offline MRN control.

        This task also includes backend configuration hardening, full test coverage, formatting, and passing CI workflows.

  - type: checkboxes
    id: feature-ui
    attributes:
      label: 🧩 Feature Development — Admin Interfaces
      options:
        - label: Create User Management page with add/edit/disable modal
        - label: Create Test Catalog page with add/edit/delete test modal
        - label: Create Lab Terminals config page with MRN range validation
        - label: Use role-gated routing (Admin only access)
        - label: All forms use Tailwind, controlled inputs, and modal UX

  - type: checkboxes
    id: integration-api
    attributes:
      label: 🔌 API Integration
      options:
        - label: Integrate `/api/users/` for CRUD users
        - label: Integrate `/api/catalog/` for test catalog entries
        - label: Integrate `/api/terminals/` for MRN terminal config
        - label: Use axios service modules with full typing

  - type: checkboxes
    id: testing
    attributes:
      label: 🧪 Testing & Type Safety
      options:
        - label: Add Vitest tests for Admin forms and pages
        - label: Add Django tests for user/catalog/terminal APIs if changed
        - label: Ensure 90%+ frontend coverage and 100% backend coverage
        - label: Confirm no use of `any` or unsafe types

  - type: checkboxes
    id: formatting
    attributes:
      label: 🧼 Linting, Formatting & Typecheck
      options:
        - label: Run `pnpm lint` and fix all errors
        - label: Run `pnpm format` for Prettier auto-fix
        - label: Run `pnpm typecheck` to confirm strict mode compatibility

  - type: checkboxes
    id: ci
    attributes:
      label: 🚦 CI Workflow Pass & Debugging
      options:
        - label: Run `pnpm test` and ensure all unit tests pass
        - label: Run `docker-compose up` and verify all containers are healthy
        - label: If any CI job fails, debug stack trace and re-run
        - label: Confirm all GitHub Actions checks are green

  - type: textarea
    id: summary
    attributes:
      label: ✅ Completion Summary
      description: Briefly describe what was implemented or fixed.
      placeholder: e.g., Created full Admin UI with test catalog and terminal config. All tests passed and CI green.
    validations:
      required: true
