
name: [Blocker] Wire Up Print Report Button
description: Enable one-click PDF report access for pathologists and reception
title: "[Blocker]: Enable Print Report via API download"
labels: ["blocker", "reporting", "pdf"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🖨️ Report Print Button Task

        The “Print” button in the Worklist and Order Detail views must trigger the backend PDF download endpoint.

  - type: checkboxes
    id: task
    attributes:
      label: 🔧 Tasks
      options:
        - label: Connect print button to `/api/reports/{id}/download/`
        - label: Ensure published results exist before enabling
        - label: Trigger browser download on click

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Final Checks
      options:
        - label: Report PDF downloads successfully
        - label: No console errors
        - label: CI green
