
name: [Blocker] Auto-Create Samples After Order
description: Ensure sample records are created immediately after order submission
title: "[Blocker]: Auto-create sample records on order"
labels: ["blocker", "workflow", "lab"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🧬 Auto-Create Sample Task

        After an order is submitted, sample records for each test must be created automatically, or users must be able to generate them from the UI.

  - type: checkboxes
    id: task
    attributes:
      label: 🔧 Tasks
      options:
        - label: On order creation, create sample records for each order item
        - label: Generate unique sample barcode per test
        - label: Ensure status is PENDING_COLLECTION
        - label: Display new samples in the Order Detail view

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Final Checks
      options:
        - label: Phlebotomy can immediately collect samples
        - label: Test written for sample creation hook
        - label: CI passing
