name: Bulk Actions — Collect, Receive, Publish, Print
description: Enable multi-order handling for sample and report workflows
title: "[Lab]: Add bulk action support for samples and reports"
labels: ["feature", "workflow", "usability"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Overview

        Add support for **bulk actions** to improve lab efficiency. This includes selecting multiple orders or samples to process with a single action (e.g. bulk collect, receive, verify, publish, print).

        This improves speed in high-volume labs.

  - type: checkboxes
    id: features
    attributes:
      label: Feature Tasks
      options:
        - label: Enable multi-select checkboxes on Lab Worklist table
        - label: Add bulk "Collect Samples" action
        - label: Add bulk "Mark as Received"
        - label: Add bulk "Verify Results" (Pathologist only)
        - label: Add bulk "Publish Results"
        - label: Add bulk "Download/Print Reports" (Admin + Reception)

  - type: checkboxes
    id: testing
    attributes:
      label: Testing & Validation
      options:
        - label: Add unit tests for selection state and button enabling
        - label: Test backend batch APIs or implement multi-ID handlers
        - label: Use sample IDs or order IDs array in payload
        - label: Ensure error handling if partial success/failure occurs

  - type: checkboxes
    id: formatting
    attributes:
      label: Formatting & Typecheck
      options:
        - label: Confirm type safety of all bulk handlers
        - label: Lint and format all modified components
        - label: Run full frontend and backend test suites

  - type: checkboxes
    id: ci
    attributes:
      label: CI & Merge
      options:
        - label: All CI jobs (lint, test, typecheck) green
        - label: Confirm user role permissions enforced
        - label: PR linked to issue and cleanly merges into `main`

  - type: textarea
    id: summary
    attributes:
      label: Completion Summary
      description: Summarize what was built and tested
